name: go-check-pods - Publish Docker image and run Helm Upgrade

on:
  push:
    branches: ['main']

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: jczuniga1992/go-check-pads
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: src
          push: true
          tags: latest
          labels: ${{ steps.meta.outputs.labels }}
      - name: Helm upgrade
        id: helm-upgrade
        run: |
          helm upgrade -i go-check-pods-release go-check-pods --values go-check-pods/values.yaml -n go-check-pods-ns